### ISSUE TITLE
关于此软件的一些问题

### ISSUE THREAD

**Issue by pureGavin** [kt007007/KTMinerProxy#2]
如果我只是单纯的自己用，并且不开抽水，那么开发者还会抽千分之三吗？

另外我看到了另一个软件和这个贼像
https://github.com/MinerProxyBTC/GoMinerTool
不知道哪个是正版，哪个是盗版

**Comment by chanywn** [comment]
free

**Comment by pureGavin** [comment]
为什么我邮箱里收到了你的回复，但是GitHub上却看不到？
另外我的第二个问题你好像还没回复 :p

**Comment by kt007007** [comment]
> 我邮箱里收到了你的回复，但是GitHub上却看不到？

币种类型有个proxy，proxy类似nginx，适用于所有币种，是没有抽水的，但同时也没有数据统计等相关信息

**Comment by pureGavin** [comment]
![image](https://user-images.githubusercontent.com/45478229/185016438-aab8b4c6-f2fd-40f7-8fcc-62b36a08ad4f.png)

**Comment by kt007007** [comment]
> ![image](https://user-images.githubusercontent.com/45478229/185016438-aab8b4c6-f2fd-40f7-8fcc-62b36a08ad4f.png)

1. 非proxy类型的端口，都会带有抽水
2. 只能说此处是原版
